name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-versions: '3.8'
          architecture: x64
      - run: pip install nox==2020.5.24
      - run: pip install poetry==1.0.5
      - run: nox --sessions tests-3.8 coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
